//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace www.otoparcabul.com.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Brand
    {
        public Brand()
        {
            this.BrandModels = new HashSet<BrandModel>();
            this.Products = new HashSet<Product>();
        }
    
        public int ID { get; set; }
        public int VehicleTypeID { get; set; }
        public string UrlName { get; set; }
        public string Name { get; set; }
        public bool IsActive { get; set; }
        public Nullable<int> ProductCount { get; set; }
    
        public virtual VehicleType VehicleType { get; set; }
        public virtual ICollection<BrandModel> BrandModels { get; set; }
        public virtual ICollection<Product> Products { get; set; }
    }
}
