//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace www.otoparcabul.com.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class City
    {
        public City()
        {
            this.Members = new HashSet<Member>();
        }
    
        public byte ID { get; set; }
        public string Name { get; set; }
        public string UrlName { get; set; }
    
        public virtual ICollection<Member> Members { get; set; }
    }
}
