//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace www.otoparcabul.com.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Member
    {
        public Member()
        {
            this.FavoriteMembers = new HashSet<FavoriteMember>();
            this.FavoriteMembers1 = new HashSet<FavoriteMember>();
            this.FavoriteProducts = new HashSet<FavoriteProduct>();
            this.Logs = new HashSet<Log>();
            this.Messages = new HashSet<Message>();
            this.Messages1 = new HashSet<Message>();
            this.Products = new HashSet<Product>();
            this.ShoppingCarts = new HashSet<ShoppingCart>();
            this.ShowStores = new HashSet<ShowStore>();
        }
    
        public int ID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string FullName { get; set; }
        public string UrlName { get; set; }
        public bool IsStore { get; set; }
        public string EMail { get; set; }
        public string Password { get; set; }
        public bool IsVerified { get; set; }
        public string VerificationCode { get; set; }
        public string Address { get; set; }
        public byte CityID { get; set; }
        public string Tel1 { get; set; }
        public string Tel2 { get; set; }
        public string Description { get; set; }
        public string LogoFileName { get; set; }
        public System.DateTime SignUpDate { get; set; }
        public System.DateTime LastLoginDate { get; set; }
        public System.DateTime LastModifiedDate { get; set; }
        public bool IsActive { get; set; }
        public bool IsAdmin { get; set; }
        public Nullable<int> ProductCount { get; set; }
        public Nullable<int> MessageCount { get; set; }
    
        public virtual City City { get; set; }
        public virtual ICollection<FavoriteMember> FavoriteMembers { get; set; }
        public virtual ICollection<FavoriteMember> FavoriteMembers1 { get; set; }
        public virtual ICollection<FavoriteProduct> FavoriteProducts { get; set; }
        public virtual ICollection<Log> Logs { get; set; }
        public virtual ICollection<Message> Messages { get; set; }
        public virtual ICollection<Message> Messages1 { get; set; }
        public virtual ICollection<Product> Products { get; set; }
        public virtual ICollection<ShoppingCart> ShoppingCarts { get; set; }
        public virtual ICollection<ShowStore> ShowStores { get; set; }
    }
}
